stages:

  prepare_data:
    cmd: python src/ricardo_ojeda_machine/pipelines/dvc_steps/prepare_data.py
    deps:
      - src/ricardo_ojeda_machine/pipelines/dvc_steps/prepare_data.py
      - data/01_raw/intakes_outcomes_raw.csv
    outs:
      - data/02_intermediate/intakes_outcomes_clean.csv

  feature_engineering:
    cmd: python src/ricardo_ojeda_machine/pipelines/dvc_steps/feature_engineering.py
    deps:
      - src/ricardo_ojeda_machine/pipelines/dvc_steps/feature_engineering.py
      - data/02_intermediate/intakes_outcomes_clean.csv
    outs:
      - data/05_model_input/features_dataset.csv

  train_models:
    cmd: python src/ricardo_ojeda_machine/pipelines/dvc_steps/train_models.py
    deps:
      - src/ricardo_ojeda_machine/pipelines/dvc_steps/train_models.py
      - data/05_model_input/features_dataset.csv
    outs:
      - 07_model_output/classification_results.csv

  evaluate:
    cmd: python src/ricardo_ojeda_machine/pipelines/dvc_steps/evaluate.py
    deps:
      - src/ricardo_ojeda_machine/pipelines/dvc_steps/evaluate.py
      - 07_model_output/classification_results.csv
    outs:
      - 08_reporting/evaluation_summary.csv
